version: "3.8"
services:
  
  snmi-bot:
    image: alekssh1fter/snmi-bot:1.1-arm
    restart: "on-failure"
    environment:
      - SPRING_CONFIG_LOCATION=file:/appconfig/application.config
    volumes:
      - snmi_bot_app_config_vol:/appconfig
  mongo-db:
    image: mongo:4.2.9
    restart: "on-failure"
    ports:
      - "27017:27017"
    volumes:
      - snmi_bot_mongo_db_vol:/data/db
      - snmi_bot_mongo_config_db_vol:/data/configdb
volumes:
  snmi_bot_mongo_db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/orangepi/myapps/snmi-bot/dockervol/db
  snmi_bot_mongo_config_db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/orangepi/myapps/snmi-bot/dockervol/dbconfig
  snmi_bot_app_config_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/orangepi/myapps/snmi-bot/dockervol/appconfig
